name: GSI Build

on: [push]

env:
  ROM_URL: https://bigota.d.miui.com/9.9.3/miui_MI8SE_9.9.3_a9d719f08b_9.0.zip
  ROM_NAME: miui
  ZIP_NAME: miui
  TZ: America/Sao_Paulo
  MIR: gof
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Initializing telegram bot
         env:
              TOKEN: ${{ secrets.BOT_TOKEN }}

         run: |
              sudo install telegram /usr/bin
              chmod +x build/initial.sh
              . build/initial.sh

       - name: Set up python
         uses: actions/setup-python@v2
         with:
           python-version: '3.8.2'
 
       - name: Install python requirements
         run: |
              pip install pyrogram tgcrypto

       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/HitaloSama/ErfanGSIs.git

       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh

       - name: Execute Shell Script
         env:
              TOKEN: ${{ secrets.BOT_TOKEN }}
              
         run: |
               chmod +x build/build.sh
               . build/build.sh

       - name: Copy and rename A-only build info
         run: cp ErfanGSIs/output/*Aonly*.txt Aonly.txt

       - name: Print A-Only build info
         run: |
              cat ErfanGSIs/output/*Aonly*.txt

       - name: Print AB build info
         run: |
              cat ErfanGSIs/output/*-AB-*.txt

       - name: Send build info to Telegram
         env:
              CHAT_ID: ${{ secrets.CHAT_ID }}
              BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
              API_ID: ${{ secrets.API_ID }}
              API_HASH: ${{ secrets.API_HASH }}
         run: |
              python .github/workflows/robot.py
